### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by blaoke** [qinyuanpei/WallPaper#1]
你好，读了你的代码，通过API爬取图片那一块client_id这个自定义名称可以请教一下是什么意思吗？通过api爬取图片是怎么实现的，有相关的教程文档可以介绍一下吗？谢谢

**Comment by qinyuanpei** [comment]
文章里写得非常详尽了，就是人家提供了接口，你去申请一个client_id，通过接口你就能拿到图片的链接，剩下的就是常规的下载了，我这里无非多了设置为壁纸这个环节。图片如果打不来，请在新窗口中打开！
